#ifndef MAIN_H
#define MAIN_H

#define WIFI_CONNECTION_ERROR -1
#define ONE_STEP 1
#define SERVER_CONNECTION_ERROR 0
#define MAX_BYTE_BEFORE_FLUSH 10
typedef enum
{
    CONNECT_TO_WIFI,
    CONNECT_TO_SERVER,
    DO_COMMANDS,

} ROBOT_STATE;

#endif